### ISSUE TITLE
Avalonia designer generates an error.

### ISSUE THREAD

**Issue by TopBaJLbD** [mysteryx93/HanumanInstitute.MvvmDialogs#9]
Hi. 
I'm using 1.4.1 version from nuget.
I use custom view locator and it works good in runtime.
``` cs
 public class ViewLocator : ViewLocatorBase
 {
        private const string ViewModelsName = "ViewModels";
        private const string ViewsName = "Views";
        private const string ViewModelName = "ViewModel";

        protected override string GetViewName(object viewModel)
        {
            string[] nameParts = viewModel.GetType().FullName!.Split('.');
            for (var itemIndex = 0; itemIndex < nameParts.Length; itemIndex++)
            {
                if (nameParts[itemIndex] == ViewModelsName)
                {
                    nameParts[itemIndex] = ViewsName;
                    continue;
                }

                if (nameParts[itemIndex].EndsWith(ViewModelName))
                {
                    nameParts[itemIndex] = nameParts[itemIndex].Substring(0, nameParts[itemIndex].Length - ViewModelName.Length);
                }
            }

            return string.Join('.', nameParts);
        }
}
```

When I work with  avalonia designer it doesn't render a view in VisualStudio.
Avalonia Diagnostics:

```
00:39:04.637 [Information]  Starting previewer process for '"D:\Projects\My Own\MyApp\MyApp\MyApp\bin\Debug\net5.0\MyApp.dll"'
00:39:04.641 [Information] 22352 Started previewer process for '"D:\Projects\My Own\MyApp\MyApp\MyApp\bin\Debug\net5.0\MyApp.dll"'. Waiting for connection to be initialized.
00:39:04.739 [Information] 22352 Connection initialized
00:39:05.379 [Error] 22352 <= "Unhandled exception. System.TypeLoadException: Dialog view of type MyApp.Views.Windows.MainWindow for view model MyApp.ViewModels.Windows.MainWindowViewModel is missing."
00:39:05.380 [Error] 22352 <= "Avalonia project template includes ViewLocator in the project base. You can customize it to map your view models to your views."
00:39:05.381 [Error] 22352 <= "   at HanumanInstitute.MvvmDialogs.Avalonia.ViewLocatorBase.Locate(Object viewModel)"
00:39:05.382 [Error] 22352 <= "   at HanumanInstitute.MvvmDialogs.DialogManagerBase`1.<>c__DisplayClass10_0.<Show>b__0()"
00:39:05.384 [Error] 22352 <= "   at HanumanInstitute.MvvmDialogs.Avalonia.DialogManager.Dispatch(Action action)"
00:39:05.384 [Error] 22352 <= "   at HanumanInstitute.MvvmDialogs.DialogManagerBase`1.Show(INotifyPropertyChanged ownerViewModel, INotifyPropertyChanged viewModel)"
00:39:05.385 [Error] 22352 <= "   at HanumanInstitute.MvvmDialogs.DialogServiceBase.ShowInternal(INotifyPropertyChanged ownerViewModel, INotifyPropertyChanged viewModel)"
00:39:05.387 [Error] 22352 <= "   at HanumanInstitute.MvvmDialogs.DialogServiceBase.Show(INotifyPropertyChanged ownerViewModel, INotifyPropertyChanged viewModel)"
00:39:05.389 [Error] 22352 <= "   at MyApp.App.OnFrameworkInitializationCompleted() in D:\Projects\My Own\MyApp\MyApp\MyApp\App.axaml.cs:line 55"
00:39:05.391 [Error] 22352 <= "   at Avalonia.Controls.AppBuilderBase`1.Setup() in /_/src/Avalonia.Controls/AppBuilderBase.cs:line 312"
00:39:05.392 [Error] 22352 <= "   at Avalonia.Controls.AppBuilderBase`1.SetupWithoutStarting() in /_/src/Avalonia.Controls/AppBuilderBase.cs:line 167"
00:39:05.394 [Error] 22352 <= "   at Avalonia.DesignerSupport.Remote.RemoteDesignerEntryPoint.AppInitializer`1.ConfigureApp(IAvaloniaRemoteTransportConnection transport, CommandLineArgs args, Object obj) in /_/src/Avalonia.DesignerSupport/Remote/RemoteDesignerEntryPoint.cs:line 154"
00:39:05.395 [Error] 22352 <= "   at Avalonia.DesignerSupport.Remote.RemoteDesignerEntryPoint.Main(String[] cmdline) in /_/src/Avalonia.DesignerSupport/Remote/RemoteDesignerEntryPoint.cs:line 179"
00:39:05.396 [Error] 22352 <= "   at Avalonia.Designer.HostApp.Program.Main(String[] args) in /_/src/tools/Avalonia.Designer.HostApp/Program.cs:line 47"
00:39:06.014 [Information]  Process exited
00:39:06.015 [Information]  Stopping previewer process
00:39:06.014 [Error]  Connection error
System.IO.IOException: Unable to read data from the transport connection: Удаленный хост принудительно разорвал существующее подключение. ---> System.Net.Sockets.SocketException: Удаленный хост принудительно разорвал существующее подключение
   at System.Net.Sockets.Socket.EndReceive(IAsyncResult asyncResult)
   at System.Net.Sockets.NetworkStream.EndRead(IAsyncResult asyncResult)
   --- End of inner exception stack trace ---
   at System.Net.Sockets.NetworkStream.EndRead(IAsyncResult asyncResult)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncTrimPromise`1.Complete(TInstance thisRef, Func`3 endMethod, IAsyncResult asyncResult, Boolean requiresSynchronization)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Avalonia.Remote.Protocol.BsonStreamTransportConnection.<ReadExact>d__15.MoveNext() in /_/src/Avalonia.Remote.Protocol/BsonStreamTransport.cs:line 56
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Avalonia.Remote.Protocol.BsonStreamTransportConnection.<Reader>d__16.MoveNext() in /_/src/Avalonia.Remote.Protocol/BsonStreamTransport.cs:line 72
```

As I understand from this log something went wrong with view mapping. It confused me a bit, because it works fine in runtime. 
@mysteryx93, any ideas?

**Comment by mysteryx93** [comment]
2 things strange here.

First, why do you call `IDialogService.Show` method at design-time to begin with?

Second, `MyApp.Views.Windows.MainWindow` does not correspond to your naming standard, why? Perhaps it's using the default ViewLocator instead of yours.

**Comment by TopBaJLbD** [comment]
Thank you.
My problem was in `App` class.

``` cs
public override void OnFrameworkInitializationCompleted()
{
    GC.KeepAlive(typeof(DialogService));

    // DialogService.Show(null, Locator.Current.GetService<MainWindowViewModel>());  <- it was wrong 
    if (ApplicationLifetime is IClassicDesktopStyleApplicationLifetime desktop)
    {
        desktop.MainWindow = new MainWindow
        {
            DataContext = Locator.Current.GetService<MainWindowViewModel>()
        };
     }

     base.OnFrameworkInitializationCompleted();
}
```

**Comment by mysteryx93** [comment]
Actually it's recommended to use `DialogService.Show` here so that `IViewLoaded` and `IViewClosed` are handled properly.

Here is how I initiate my app.

https://github.com/mysteryx93/HanumanInstituteApps/blob/master/Common.Avalonia.App/Common/CommonApplication.cs

I note this code I added.

```
#if DEBUG
        // Required by Avalonia XAML editor to recognize custom XAML namespaces. Until they fix the problem.
        GC.KeepAlive(typeof(EventTriggerBehavior));

        if (Design.IsDesignMode)
        {
            base.OnFrameworkInitializationCompleted();
            return;
        }
#endif
```

Is that absolutely required to avoid the problem you had? If that's the case, I should better document the issue.

**Comment by TopBaJLbD** [comment]
You are correct. 
My issue fully resolved. As you mentioned before, root cause of the problem was a call of `IDialogService.Show` at design-time. This is good idea to add some information, maybe with example, to the documentation. It can help others to avoid this error.

**Comment by JGKle** [comment]
I had this issue too, spent a huge amount of time trying to figure out why the designer kept crashing. Finally dug up this issue, which was the solution. Seems like it should be in the documentation/sample code...

**Comment by mysteryx93** [comment]
Perhaps the library could discard such calls at design-time to avoid that problem.
